### PR TITLE
Fix #377; db must contain hash + type, not just hash.

### LINKED ISSUE #377: P2PKH scripts paying P2SH redeemScripts are shown in balance.
For example, there are many spam transactions on the blockchain that use a redeemScript in the P2PKH fashion:

```
OP_DUP OP_HASH160 <redeemScript> OP_EQUALVERIFY OP_CHECKSIG
```

This will not be redeemable by a P2SH address, because its script must be:

```
OP_HASH160 <redeemScript> OP_EQUAL
```

This is a critical bug IMO as balances on addresses are being reported incorrectly. Any services relying on an Insight service may incorrectly credit an address with a balance it is not actually able to spend.

We should be checking the version type of the address when crediting an output to ensure it is actually spendable.

### PR DESCRIPTION
**Pull request by STRML**
Prevents erroneous crediting of all transactions to both the
p2pkh and the corresponding p2sh address.

In order to do so, the DB must also contain the hash type. This will require a DB rebuild.

See #377

### CODE REVIEW

**Comment by STRML** [comment]
Note that this changes some internal APIs.

`getInputs()` and `getOutputs()` haven't changed, so there shouldn't be any breakage in insight-api, but the arity of `_getInputsMempool()` and `_getOutputsMempool()` has changed to include the `hashTypeBuffer`.

Additionally, `getInputs()` and `getOutputs()` now yield objects with a `hashType` string, which is identical to the strings used in bitcore.Address.

**Comment by STRML** [comment]
Here's an easy (low block height) address that shows an erroneous balance: https://test-insight.bitpay.com/address/2N1d4nqHgVUqY5HaUKmRpD69RMeigkYZKk4

**Comment by STRML** [comment]
Rebased due to a test error in _getOutputsMempool, all tests green now.

**Comment by braydonf** [comment]
Good find. And yes for optimization the database stores the hash only, as the probability of a collision between the hash of a public key to the hash of a script is extremely low. However it does come with the unintentional affect that both will query to the same balance.

https://test-insight.bitpay.com/address/2N1d4nqHgVUqY5HaUKmRpD69RMeigkYZKk4
```
{ 
  hash: '5be27ad49c77a1fe275e59a02f79be1ce9aaa430',
  type: 'scripthash',
  network: 'testnet' 
}
```

https://test-insight.bitpay.com/address/moto6bxC99T4ZSj7F77izS1YrmpWQKxnGk

```
{ 
  hash: '5be27ad49c77a1fe275e59a02f79be1ce9aaa430',
  type: 'pubkeyhash',
  network: 'testnet' 
}
```

**Comment by STRML** [comment]
@braydonf Low, but it does happen. And it appears there are some massive txs on the blockchain that intentionally target this, which is how I found it - one of my addresses has an incorrect balance because of this bug.

**Comment by STRML** [comment]
I've just finished reindexing Testnet with this patch on our local instance - you have to wipe the leveldb directories due to the change informat. Balances are showing up correctly and the affected addresses are now fixed.

**Comment by STRML** [comment]
Finished reindexing production, DB size is 54GB. Issue is fixed properly for us and all is running well.

**Comment by braydonf** [comment]
Finished syncing with testnet and can confirm that this fixes the issue.

File: lib/services/address/index.js [hunk 1]
```diff
@@ -698,6 +732,26 @@ AddressService.prototype._decodeInputValueMap = function(buffer) {
...
+      hashTypeBuffer = new Buffer(hashTypes[i], 'hex');
+      break;
+    }
+  }
+  return {
+    hashBuffer: addrObj.hashBuffer,
+    hashTypeBuffer: hashTypeBuffer,
+    hashTypeReadable: addrObj.type
+  };
+}
```
Comment (braydonf) [inline lib/services/address/index.js]: nit: missing semicolon

File: lib/services/address/index.js [hunk 2]
```diff
@@ -698,6 +732,26 @@ AddressService.prototype._decodeInputValueMap = function(buffer) {
   };
 };
 
+AddressService.prototype._getAddressInfo = function(addressStr) {
+  var addrObj = bitcore.Address(addressStr);
+  var hashbuffer = addrObj.hashBuffer;
+
+  // Find our internal encoding for this hash type
+  var hashTypes = Object.keys(AddressService.HASH_TYPES_READABLE);
```
Comment (braydonf) [inline lib/services/address/index.js]: Any reason we shouldn't add another constant for this, e.g.:
```js
AddressService.HASH_TYPES_MAP = {
  'pubkeyhash': AddressService.HASH_TYPES.PUBKEY,
  'scripthash': AddressService.HASH_TYPES.REDEEMSCRIPT
};
```
So this can just be:
```js
var hashTypeBuffer = AddressService.HASH_TYPES_MAP[addrObj.type];
```

File: lib/services/address/index.js [hunk 3]
```diff
@@ -902,6 +956,7 @@ AddressService.prototype.getInputForOutput = function(txid, outputIndex, options
 /**
  * Will give inputs that spend previous outputs for an address as an object with:
  *   address - The base58check encoded address
+ *   hashtype - The type of the address, e.g. 'pubkeyhash' or 'scripthash'
```
Comment (braydonf) [inline lib/services/address/index.js]: hashType

File: lib/services/address/index.js [hunk 4]
```diff
@@ -1082,6 +1148,7 @@ AddressService.prototype._getSpentMempool = function(txidBuffer, outputIndex, ca
 /**
  * Will give outputs for an address as an object with:
  *   address - The base58check encoded address
+ *   hashtype - The type of the address, e.g. 'pubkeyhash' or 'scripthash'
```
Comment (braydonf) [inline lib/services/address/index.js]: the property returned is in camelcase: `hashType`

**Comment by braydonf** [comment]
Aside from a few small nits, it looks good to me. Will also test with livenet soon. I think we should include this in the next major release, since even though a collision is improbable, it's possible to create unspendable collisions easily. We also add a command for reindexing (spawned an issue for that: https://github.com/bitpay/bitcore-node/issues/388).

File: lib/services/address/index.js [hunk 5]
```diff
@@ -698,6 +732,26 @@ AddressService.prototype._decodeInputValueMap = function(buffer) {
   };
 };
 
+AddressService.prototype._getAddressInfo = function(addressStr) {
+  var addrObj = bitcore.Address(addressStr);
+  var hashbuffer = addrObj.hashBuffer;
```
Comment (braydonf) [inline lib/services/address/index.js]: nit: variable isn't used anymore

**Comment by STRML** [comment]
@braydonf Fixed nits as above, added `HASH_TYPE_MAP` per your suggestion.

**Comment by braydonf** [comment]
LGTM. I've been building from this branch for a week or more on livenet and testnet.

**Comment by STRML** [comment]
:+1: :shipit:!

**Comment by kleetus** [comment]
merging!
